name: Deploy Store App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy updated files to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.90.17.164 'sudo chmod -R 775 /var/www/store-app'
        ssh -i ~/.ssh/id_rsa ubuntu@3.90.17.164 'sudo chown -R ubuntu:ubuntu /var/www/store-app'
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no store-app/app.js ubuntu@3.90.17.164 :/var/www/store-app/app.js

    - name: Restart Node.js app
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164  "pm2 restart store-app || pm2 start /var/www/store-app/app.js --name store-app"

    - name: Reload Nginx
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 "sudo systemctl reload nginx"
