name: Deploy Store App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Debug SSH Setup
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa || echo "id_rsa not found or empty"
        ssh -T git@github.com || echo "SSH authentication failed"

    - name: Configure npm Global Directory
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'mkdir -p ~/.npm-global'
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'npm config set prefix ~/.npm-global'
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'echo "export PATH=~/.npm-global/bin:$PATH" >> ~/.profile'
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'source ~/.profile'

    - name: Install PM2 on EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'sudo npm install -g pm2'
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'which pm2 || echo "PM2 not found"'

    - name: Verify File Transfer
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no store-app/app.js ubuntu@3.90.17.164:/var/www/store-app/app.js
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'ls -la /var/www/store-app'
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'cat /var/www/store-app/app.js'

    - name: Restart Node.js app
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 "pm2 restart store-app || pm2 start /var/www/store-app/app.js --name store-app"
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 'pm2 list'

    - name: Reload Nginx
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.90.17.164 "sudo systemctl reload nginx || echo 'Failed to reload Nginx'"
